//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDINMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DemoDBEntities1 : DbContext
    {
        public DemoDBEntities1()
            : base("name=DemoDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual int sp_delete_tblCategory(Nullable<int> cATEGORY_ID)
        {
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_tblCategory", cATEGORY_IDParameter);
        }
    
        public virtual int sp_delete_tblProduct(Nullable<int> pROD_ID)
        {
            var pROD_IDParameter = pROD_ID.HasValue ?
                new ObjectParameter("PROD_ID", pROD_ID) :
                new ObjectParameter("PROD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_tblProduct", pROD_IDParameter);
        }
    
        public virtual int sp_Insert_tblCategory(string cATEGORY_NAME)
        {
            var cATEGORY_NAMEParameter = cATEGORY_NAME != null ?
                new ObjectParameter("CATEGORY_NAME", cATEGORY_NAME) :
                new ObjectParameter("CATEGORY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_tblCategory", cATEGORY_NAMEParameter);
        }
    
        public virtual int sp_Insert_tblProduct(string pROD_NAME, Nullable<decimal> pROD_PRICE, Nullable<int> pROD_UNIT, Nullable<int> pROD_CATEGORY_ID)
        {
            var pROD_NAMEParameter = pROD_NAME != null ?
                new ObjectParameter("PROD_NAME", pROD_NAME) :
                new ObjectParameter("PROD_NAME", typeof(string));
    
            var pROD_PRICEParameter = pROD_PRICE.HasValue ?
                new ObjectParameter("PROD_PRICE", pROD_PRICE) :
                new ObjectParameter("PROD_PRICE", typeof(decimal));
    
            var pROD_UNITParameter = pROD_UNIT.HasValue ?
                new ObjectParameter("PROD_UNIT", pROD_UNIT) :
                new ObjectParameter("PROD_UNIT", typeof(int));
    
            var pROD_CATEGORY_IDParameter = pROD_CATEGORY_ID.HasValue ?
                new ObjectParameter("PROD_CATEGORY_ID", pROD_CATEGORY_ID) :
                new ObjectParameter("PROD_CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_tblProduct", pROD_NAMEParameter, pROD_PRICEParameter, pROD_UNITParameter, pROD_CATEGORY_IDParameter);
        }
    
        public virtual ObjectResult<sp_Select_tblCategory_Result> sp_Select_tblCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_tblCategory_Result>("sp_Select_tblCategory");
        }
    
        public virtual ObjectResult<sp_Select_tblProduct_Result> sp_Select_tblProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_tblProduct_Result>("sp_Select_tblProduct");
        }
    
        public virtual int sp_Update_tblCategory(Nullable<int> cATEGORY_ID, string cATEGORY_NAME)
        {
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(int));
    
            var cATEGORY_NAMEParameter = cATEGORY_NAME != null ?
                new ObjectParameter("CATEGORY_NAME", cATEGORY_NAME) :
                new ObjectParameter("CATEGORY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_tblCategory", cATEGORY_IDParameter, cATEGORY_NAMEParameter);
        }
    
        public virtual int sp_Update_tblProduct(Nullable<int> pROD_ID, string pROD_NAME, Nullable<decimal> pROD_PRICE, Nullable<int> pROD_UNIT, Nullable<int> pROD_CATEGORY_ID)
        {
            var pROD_IDParameter = pROD_ID.HasValue ?
                new ObjectParameter("PROD_ID", pROD_ID) :
                new ObjectParameter("PROD_ID", typeof(int));
    
            var pROD_NAMEParameter = pROD_NAME != null ?
                new ObjectParameter("PROD_NAME", pROD_NAME) :
                new ObjectParameter("PROD_NAME", typeof(string));
    
            var pROD_PRICEParameter = pROD_PRICE.HasValue ?
                new ObjectParameter("PROD_PRICE", pROD_PRICE) :
                new ObjectParameter("PROD_PRICE", typeof(decimal));
    
            var pROD_UNITParameter = pROD_UNIT.HasValue ?
                new ObjectParameter("PROD_UNIT", pROD_UNIT) :
                new ObjectParameter("PROD_UNIT", typeof(int));
    
            var pROD_CATEGORY_IDParameter = pROD_CATEGORY_ID.HasValue ?
                new ObjectParameter("PROD_CATEGORY_ID", pROD_CATEGORY_ID) :
                new ObjectParameter("PROD_CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_tblProduct", pROD_IDParameter, pROD_NAMEParameter, pROD_PRICEParameter, pROD_UNITParameter, pROD_CATEGORY_IDParameter);
        }
    
        public virtual ObjectResult<sp_details_tblCategory_Result> sp_details_tblCategory(Nullable<int> cATEGORY_ID)
        {
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_details_tblCategory_Result>("sp_details_tblCategory", cATEGORY_IDParameter);
        }
    
        public virtual ObjectResult<sp_details_tblProduct_Result> sp_details_tblProduct(Nullable<int> pROD_ID)
        {
            var pROD_IDParameter = pROD_ID.HasValue ?
                new ObjectParameter("PROD_ID", pROD_ID) :
                new ObjectParameter("PROD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_details_tblProduct_Result>("sp_details_tblProduct", pROD_IDParameter);
        }
    
        public virtual ObjectResult<sp_tblProduct_data_Result> sp_tblProduct_data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblProduct_data_Result>("sp_tblProduct_data");
        }
    }
}
